// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/yaninyzwitty/temporal-durable-event-pipeline/internal/handler (interfaces: EventStore)
//
// Generated by this command:
//
//	mockgen -destination internal/handler/mock_event_store.go -package handler github.com/yaninyzwitty/temporal-durable-event-pipeline/internal/handler EventStore
//

// Package handler is a generated GoMock package.
package handler

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	repository "github.com/yaninyzwitty/temporal-durable-event-pipeline/internal/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockEventStore is a mock of EventStore interface.
type MockEventStore struct {
	ctrl     *gomock.Controller
	recorder *MockEventStoreMockRecorder
	isgomock struct{}
}

// MockEventStoreMockRecorder is the mock recorder for MockEventStore.
type MockEventStoreMockRecorder struct {
	mock *MockEventStore
}

// NewMockEventStore creates a new mock instance.
func NewMockEventStore(ctrl *gomock.Controller) *MockEventStore {
	mock := &MockEventStore{ctrl: ctrl}
	mock.recorder = &MockEventStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventStore) EXPECT() *MockEventStoreMockRecorder {
	return m.recorder
}

// CreateEvent mocks base method.
func (m *MockEventStore) CreateEvent(ctx context.Context, eventType string, payload []byte) (repository.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEvent", ctx, eventType, payload)
	ret0, _ := ret[0].(repository.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEvent indicates an expected call of CreateEvent.
func (mr *MockEventStoreMockRecorder) CreateEvent(ctx, eventType, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEvent", reflect.TypeOf((*MockEventStore)(nil).CreateEvent), ctx, eventType, payload)
}

// GetEventByID mocks base method.
func (m *MockEventStore) GetEventByID(ctx context.Context, id uuid.UUID) (repository.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEventByID", ctx, id)
	ret0, _ := ret[0].(repository.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEventByID indicates an expected call of GetEventByID.
func (mr *MockEventStoreMockRecorder) GetEventByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEventByID", reflect.TypeOf((*MockEventStore)(nil).GetEventByID), ctx, id)
}

// ListEvents mocks base method.
func (m *MockEventStore) ListEvents(ctx context.Context, limit, offset int32) ([]repository.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEvents", ctx, limit, offset)
	ret0, _ := ret[0].([]repository.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEvents indicates an expected call of ListEvents.
func (mr *MockEventStoreMockRecorder) ListEvents(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEvents", reflect.TypeOf((*MockEventStore)(nil).ListEvents), ctx, limit, offset)
}

// PollPendingEvents mocks base method.
func (m *MockEventStore) PollPendingEvents(ctx context.Context, limit int32) ([]repository.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PollPendingEvents", ctx, limit)
	ret0, _ := ret[0].([]repository.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PollPendingEvents indicates an expected call of PollPendingEvents.
func (mr *MockEventStoreMockRecorder) PollPendingEvents(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PollPendingEvents", reflect.TypeOf((*MockEventStore)(nil).PollPendingEvents), ctx, limit)
}

// UpdateEventStatus mocks base method.
func (m *MockEventStore) UpdateEventStatus(ctx context.Context, id uuid.UUID, status repository.EventStatus) (repository.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEventStatus", ctx, id, status)
	ret0, _ := ret[0].(repository.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateEventStatus indicates an expected call of UpdateEventStatus.
func (mr *MockEventStoreMockRecorder) UpdateEventStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEventStatus", reflect.TypeOf((*MockEventStore)(nil).UpdateEventStatus), ctx, id, status)
}
