// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/yaninyzwitty/temporal-durable-event-pipeline/internal/handler (interfaces: OrderStore)
//
// Generated by this command:
//
//	mockgen -destination internal/handler/mock_order_store.go -package handler github.com/yaninyzwitty/temporal-durable-event-pipeline/internal/handler OrderStore
//

// Package handler is a generated GoMock package.
package handler

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	pgtype "github.com/jackc/pgx/v5/pgtype"
	repository "github.com/yaninyzwitty/temporal-durable-event-pipeline/internal/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockOrderStore is a mock of OrderStore interface.
type MockOrderStore struct {
	ctrl     *gomock.Controller
	recorder *MockOrderStoreMockRecorder
	isgomock struct{}
}

// MockOrderStoreMockRecorder is the mock recorder for MockOrderStore.
type MockOrderStoreMockRecorder struct {
	mock *MockOrderStore
}

// NewMockOrderStore creates a new mock instance.
func NewMockOrderStore(ctrl *gomock.Controller) *MockOrderStore {
	mock := &MockOrderStore{ctrl: ctrl}
	mock.recorder = &MockOrderStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderStore) EXPECT() *MockOrderStoreMockRecorder {
	return m.recorder
}

// CreateOrder mocks base method.
func (m *MockOrderStore) CreateOrder(ctx context.Context, userID uuid.UUID, totalAmount string) (repository.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrder", ctx, userID, totalAmount)
	ret0, _ := ret[0].(repository.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrder indicates an expected call of CreateOrder.
func (mr *MockOrderStoreMockRecorder) CreateOrder(ctx, userID, totalAmount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrder", reflect.TypeOf((*MockOrderStore)(nil).CreateOrder), ctx, userID, totalAmount)
}

// CreateOrderItem mocks base method.
func (m *MockOrderStore) CreateOrderItem(ctx context.Context, orderID, productID uuid.UUID, quantity int32, unitPrice string) (repository.OrderItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrderItem", ctx, orderID, productID, quantity, unitPrice)
	ret0, _ := ret[0].(repository.OrderItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrderItem indicates an expected call of CreateOrderItem.
func (mr *MockOrderStoreMockRecorder) CreateOrderItem(ctx, orderID, productID, quantity, unitPrice any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrderItem", reflect.TypeOf((*MockOrderStore)(nil).CreateOrderItem), ctx, orderID, productID, quantity, unitPrice)
}

// DeleteOrder mocks base method.
func (m *MockOrderStore) DeleteOrder(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOrder", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOrder indicates an expected call of DeleteOrder.
func (mr *MockOrderStoreMockRecorder) DeleteOrder(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOrder", reflect.TypeOf((*MockOrderStore)(nil).DeleteOrder), ctx, id)
}

// DeleteOrderItem mocks base method.
func (m *MockOrderStore) DeleteOrderItem(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOrderItem", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOrderItem indicates an expected call of DeleteOrderItem.
func (mr *MockOrderStoreMockRecorder) DeleteOrderItem(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOrderItem", reflect.TypeOf((*MockOrderStore)(nil).DeleteOrderItem), ctx, id)
}

// GetOrderByID mocks base method.
func (m *MockOrderStore) GetOrderByID(ctx context.Context, id uuid.UUID) (repository.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderByID", ctx, id)
	ret0, _ := ret[0].(repository.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderByID indicates an expected call of GetOrderByID.
func (mr *MockOrderStoreMockRecorder) GetOrderByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderByID", reflect.TypeOf((*MockOrderStore)(nil).GetOrderByID), ctx, id)
}

// GetOrderItemsByOrderID mocks base method.
func (m *MockOrderStore) GetOrderItemsByOrderID(ctx context.Context, orderID uuid.UUID) ([]repository.OrderItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderItemsByOrderID", ctx, orderID)
	ret0, _ := ret[0].([]repository.OrderItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderItemsByOrderID indicates an expected call of GetOrderItemsByOrderID.
func (mr *MockOrderStoreMockRecorder) GetOrderItemsByOrderID(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderItemsByOrderID", reflect.TypeOf((*MockOrderStore)(nil).GetOrderItemsByOrderID), ctx, orderID)
}

// ListOrdersByUser mocks base method.
func (m *MockOrderStore) ListOrdersByUser(ctx context.Context, userID uuid.UUID) ([]repository.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOrdersByUser", ctx, userID)
	ret0, _ := ret[0].([]repository.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOrdersByUser indicates an expected call of ListOrdersByUser.
func (mr *MockOrderStoreMockRecorder) ListOrdersByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOrdersByUser", reflect.TypeOf((*MockOrderStore)(nil).ListOrdersByUser), ctx, userID)
}

// UpdateOrderItemQuantity mocks base method.
func (m *MockOrderStore) UpdateOrderItemQuantity(ctx context.Context, id uuid.UUID, quantity int32) (repository.OrderItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrderItemQuantity", ctx, id, quantity)
	ret0, _ := ret[0].(repository.OrderItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOrderItemQuantity indicates an expected call of UpdateOrderItemQuantity.
func (mr *MockOrderStoreMockRecorder) UpdateOrderItemQuantity(ctx, id, quantity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrderItemQuantity", reflect.TypeOf((*MockOrderStore)(nil).UpdateOrderItemQuantity), ctx, id, quantity)
}

// UpdateOrderStatus mocks base method.
func (m *MockOrderStore) UpdateOrderStatus(ctx context.Context, id uuid.UUID, status pgtype.Text) (repository.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrderStatus", ctx, id, status)
	ret0, _ := ret[0].(repository.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOrderStatus indicates an expected call of UpdateOrderStatus.
func (mr *MockOrderStoreMockRecorder) UpdateOrderStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrderStatus", reflect.TypeOf((*MockOrderStore)(nil).UpdateOrderStatus), ctx, id, status)
}
