// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Event struct {
	ID          pgtype.UUID      `json:"id"`
	EventType   string           `json:"event_type"`
	Payload     []byte           `json:"payload"`
	Status      pgtype.Text      `json:"status"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	ProcessedAt pgtype.Timestamp `json:"processed_at"`
}

type Order struct {
	ID          pgtype.UUID      `json:"id"`
	UserID      pgtype.UUID      `json:"user_id"`
	OrderDate   pgtype.Timestamp `json:"order_date"`
	Status      pgtype.Text      `json:"status"`
	TotalAmount pgtype.Numeric   `json:"total_amount"`
}

type OrderItem struct {
	ID        pgtype.UUID    `json:"id"`
	OrderID   pgtype.UUID    `json:"order_id"`
	ProductID pgtype.UUID    `json:"product_id"`
	Quantity  int32          `json:"quantity"`
	UnitPrice pgtype.Numeric `json:"unit_price"`
}

type Product struct {
	ID            pgtype.UUID      `json:"id"`
	Name          string           `json:"name"`
	Description   pgtype.Text      `json:"description"`
	Price         pgtype.Numeric   `json:"price"`
	StockQuantity pgtype.Int4      `json:"stock_quantity"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

type User struct {
	ID           pgtype.UUID      `json:"id"`
	Username     string           `json:"username"`
	Email        string           `json:"email"`
	PasswordHash string           `json:"password_hash"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}
